from marshmallow.exceptions import SCHEMA as SCHEMA
from typing import Any, Optional

class ErrorStore:
    errors: Any = ...
    def __init__(self) -> None: ...
    def store_error(self, messages: Any, field_name: Any = ..., index: Optional[Any] = ...) -> None: ...

def merge_errors(errors1: Any, errors2: Any): ...
