from collections.abc import MutableSet
from typing import Any, Optional

class OrderedSet(MutableSet):
    end: Any = ...
    map: Any = ...
    def __init__(self, iterable: Optional[Any] = ...) -> None: ...
    def __len__(self): ...
    def __contains__(self, key: Any): ...
    def add(self, key: Any) -> None: ...
    def discard(self, key: Any) -> None: ...
    def __iter__(self) -> Any: ...
    def __reversed__(self) -> None: ...
    def pop(self, last: bool = ...): ...
    def __eq__(self, other: Any) -> Any: ...
